import random

from app.models.post import Post
from app.models.company import Company

def generate_author_id():
    return random.randint(1, 6)


forum_posts = [
    Post("Seeking Advice: Navigating the Tech Job Hunt Maze", "Hey everyone, I'm currently in the midst of searching for tech jobs, and I feel like I'm wandering through a maze without a map! Does anyone have any tips or advice for navigating the job market? I'm not quite sure where to start or what companies to look into. Any insights would be greatly appreciated!", generate_author_id()),
    Post("Interview Jitters: Anyone Else Nervous?", "Hey folks, I've got my first tech interview coming up, and I'm feeling super nervous! I've been studying like crazy, but I'm still worried about freezing up or blanking out during the interview. Any tips for staying calm and confident under pressure? How did you all deal with interview nerves?", generate_author_id()),
    Post("Prepping for the Unknown: Tech Interview Tips Needed", "Hey there, I've been doing some research on tech interviews, but I still feel like I'm going into it blind. What kinds of questions should I expect? Any tips for preparing? I want to make sure I'm as ready as possible. Any advice would be greatly appreciated!", generate_author_id()),
    Post("Company Insights Needed: Anyone Familiar with Wells-Fargo?", "Hey everyone, I've been researching companies to apply to, and Wells-Fargo caught my eye. Does anyone have any insights into what it's like to work there? What's the company culture like, and what kinds of tech roles do they typically hire for? Any info would be super helpful!", generate_author_id()),
    Post("Feeling Lost: Truist Interview Coming Up", "Hey folks, I've got an interview with Truist next week, and I'm feeling totally lost. I'm not sure what to expect or how to prepare. Has anyone interviewed with them before? Any insights into the interview process or what they're looking for in candidates? Any advice would be much appreciated!", generate_author_id()),
    Post("The Dreaded Whiteboard Interview: Help!", "Hey everyone, I've heard horror stories about whiteboard interviews, and now I've got one coming up. I'm freaking out! Any tips for preparing? How can I make sure I don't freeze up or make a fool of myself? Any advice would be greatly appreciated!", generate_author_id()),
    Post("Google Interview: What Should I Expect?", "Hey folks, I've got an interview with Google coming up, and I'm feeling both excited and terrified. What kinds of questions should I expect? Any tips for preparing? I want to make sure I'm ready for whatever they throw at me. Any insights would be greatly appreciated!", generate_author_id()),
    Post("The Tech Resume Struggle: Anyone Else Feeling Stuck?", "Hey there, I've been working on my tech resume, and I feel like I'm banging my head against a wall. I'm not sure what to include or how to format it to stand out. Any advice on crafting a killer tech resume? What are recruiters really looking for? Any tips would be much appreciated!", generate_author_id()),
    Post("Overwhelmed by Coding Challenges: Help Needed", "Hey everyone, I've been practicing coding problems, but I still feel totally overwhelmed by them. I'm worried I'll freeze up during the interview and forget everything I've learned. Any tips for mastering coding challenges? How can I build up my confidence? Any advice would be greatly appreciated!", generate_author_id()),
    Post("Technical Screen Anxiety: Anyone Else Feeling It?", "Hey folks, I've got a technical screen coming up, and I'm feeling majorly anxious about it. I'm worried I'll completely bomb it and ruin my chances. Any tips for preparing? How can I make sure I'm ready for whatever they throw at me? Any insights would be much appreciated!", generate_author_id()),
    Post("From Application to Offer: Feeling Stuck in Limbo", "Hey there, I've been applying to tech jobs like crazy, but I haven't heard back from anyone yet. I'm starting to feel like I'm stuck in limbo. Is this normal, or should I be worried? Any advice on how to stay motivated and keep pushing forward? Any insights would be much appreciated!", generate_author_id()),
    Post("Inside the Google Interview: What's It Really Like?", "Hey everyone, I've got an interview with Google coming up, and I'm dying to know what it's really like. What kinds of questions do they ask? Is it as intense as everyone says? Any tips for preparing? I want to make sure I'm ready for whatever they throw at me. Any insights would be greatly appreciated!", generate_author_id()),
    Post("Seeking Insight: Anyone Familiar with The Hartford?", "Hey folks, I'm considering applying to The Hartford, but I don't know much about them. Does anyone have any insights into what it's like to work there? What kinds of tech roles do they typically hire for? Any info would be super helpful!", generate_author_id()),
    Post("Feeling Overwhelmed: Truist Interview Tomorrow", "Hey there, My interview with Truist is tomorrow, and I'm feeling totally overwhelmed. I've been studying like crazy, but I'm still worried I'll mess it up. Any last-minute tips or words of encouragement? I could really use some support right now!", generate_author_id()),
    Post("The Tech Interview Rollercoaster: Anyone Else Riding It?", "Hey everyone, The tech interview process is such a rollercoaster of emotions, am I right? One minute, I'm feeling confident and prepared, and the next, I'm doubting everything. Anyone else riding this crazy ride? How do you cope with the ups and downs? Any advice would be greatly appreciated!", generate_author_id())
]
